apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-prometheus
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  prometheus-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        uid: PROMETHEUS_DS
        url: http://prometheus-server.monitoring.svc.cluster.local
        isDefault: true
        editable: false
        jsonData:
          timeInterval: 30s
          httpMethod: POST
          manageAlerts: true
          prometheusType: Prometheus
          cacheLevel: 'Low'
          exemplarTraceIdDestinations:
            - name: traceID
              datasourceUid: tempo
        version: 1
        readOnly: false
